name: Console Log Checker

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  console-log-check:
    name: Check for console.log()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create ESLint configuration
        run: |
          echo '{ "rules": { "no-console": "error" } }' > .eslintrc.json

      - name: Install ESLint
        run: npm install eslint

      - name: Install ESLint react plugin
        run: npm install eslint-plugin-react@latest --save-dev

      - name: Install ESLint react-hooks plugin
        run: npm install eslint-plugin-react-hooks@latest --save-dev

      - name: Install ESLint react-refresh plugin
        run: npm install eslint-plugin-react-refresh@latest --save-dev

      - name: Lint with ESLint
        run:  npx eslint . --ext .js --format=unix --no-error-on-unmatched-pattern
